version: '3.1'

services:
  db-postgres:
    image: postgres:14-alpine
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - emailln-go:/data/postgres
    ports:
      - "${DB_PORT}:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  emailln-go: